version: "3"
services:
  web:
    build: ./client
    ports:
      - "1234:1234"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    
  server:
    image: common_server_image
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db

  refresh-server:
    image: common_server_image
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - server
    # yarn generate, initialize prisma client
    command: ["sh", "-c", "yarn generate && yarn refresh-server"]

  db:
    image: postgres:12.0-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=postgres
