version: "3"
services:
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
    ports:
      - "1234:1234"

  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    ports:
      - "3000:3000"
      - "4000:4000"

  db:
    image: postgres:12.0-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_DB=${DATABASE_DB}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
