version: "3"
services:
  web:
    build: ./client
    ports:
      - "1234:1234"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    image: hackernews-clone_server
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
    command: ["sh", "-c", "yarn initDB && yarn dev"]

  refresh-server:
    image: hackernews-clone_server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - server
    # yarn generate, initialize prisma client
    command: ["sh", "-c", "yarn generate && yarn refresh-server:dev"]

  update-rankings:
    image: hackernews-clone_server
    volumes:
      - ./server/src/services/updateRankings.ts:/app/src/services/updateRankings.ts
    depends_on:
      - server
    command: ["sh", "-c", "yarn generate && yarn update-rankings:dev"]

  db:
    image: postgres:12.0-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=postgres
